<?php
return array(
    // nav
    'nav_dashboard' => 'Dashboard', 'nav_campaigns' => 'Campaigns', 'nav_quick' => 'Quick call', 'nav_audio' => 'Audio files', 'nav_dnc' => 'Do-not-call list',
    'nav_reports' => 'Reports', 'nav_settings' => 'Settings', 'nav_users' => 'Users', 'nav_api' => 'API keys', 'nav_system' => 'System',
    // auth
    'login' => 'Sign in', 'logout' => 'Sign out', 'username' => 'Username', 'password' => 'Password', 'login_intro' => 'Outbound campaign manager for Issabel / Elastix',
    'login_failed' => 'Invalid username or password', 'login_locked' => 'Too many attempts. Try again later.', 'login_root_hint' => "Superuser of this app: 'root'.", 'login_issabel_hint' => 'Issabel panel users (e.g. admin) can sign in with their panel password.',
    'forbidden' => 'You do not have permission for this action', 'not_found' => 'Page not found', 'csrf_failed' => 'Form expired, please try again', 'server_error' => 'Internal error, see logs', 'back_home' => 'Back to dashboard',
    'role_admin' => 'Administrator', 'role_operator' => 'Operator', 'role_viewer' => 'Viewer',
    'role_admin_desc' => 'Everything, including settings, users and deleting campaigns.', 'role_operator_desc' => 'Create/run campaigns, audio, DNC, API keys.', 'role_viewer_desc' => 'Read-only access to campaigns and reports.',
    // common
    'minutes' => 'min', 'list_sep' => ', ', 'no_date_limit' => 'no start/end date',
    'save' => 'Save', 'saved' => 'Saved', 'cancel' => 'Cancel', 'delete' => 'Delete', 'deleted' => 'Deleted', 'edit' => 'Edit', 'create' => 'Create', 'add' => 'Add', 'done' => 'Done', 'yes' => 'Yes', 'no' => 'No', 'on' => 'On', 'off' => 'Off',
    'name' => 'Name', 'description' => 'Description', 'status' => 'Status', 'search' => 'Search…', 'filter' => 'Filter', 'all' => 'All', 'all_statuses' => 'All statuses', 'nothing_here' => 'Nothing here yet', 'none' => 'None',
    'created_at' => 'Created', 'created_by' => 'By', 'started_at' => 'Started', 'finished_at' => 'Finished', 'time' => 'Time', 'count' => 'Count', 'title' => 'Title', 'key' => 'Key', 'tag' => 'Tag', 'target' => 'Target', 'action' => 'Action',
    'phone' => 'Phone', 'contacts' => 'Contacts', 'audio' => 'Audio', 'campaign' => 'Campaign', 'progress' => 'Progress', 'answered' => 'Answered', 'duration' => 'Duration', 'dtmf' => 'Key pressed', 'result_tag' => 'Result',
    'hangup_cause' => 'Hangup cause', 'raw_phone' => 'Original number', 'attempts' => 'Attempts', 'attempt' => 'Attempt', 'last_attempt' => 'Last attempt', 'answered_at' => 'Answered at', 'ended_at' => 'Ended at', 'channel' => 'Channel', 'note' => 'Note',
    'invalid_input' => 'Invalid input', 'unknown_action' => 'Unknown action', 'confirm_delete' => 'Delete permanently?', 'confirm_stop' => 'Stop this campaign? Pending numbers will be cancelled.', 'confirm_clear' => 'Remove all contacts and call history of this campaign?',
    'upload_error' => 'Upload failed', 'file_too_big' => 'File too big', 'file' => 'File', 'upload' => 'Upload', 'size' => 'Size', 'play' => 'Play', 'rename' => 'Rename', 'source' => 'Source', 'reason' => 'Reason', 'user' => 'User', 'users' => 'Users', 'role' => 'Role', 'active' => 'Active',
    // dashboard
    'calls_today' => 'Calls today', 'talk_time' => 'Talk time', 'active_campaigns' => 'Active campaigns', 'no_active_campaigns' => 'No active campaigns', 'live_calls' => 'Live calls', 'no_live_calls' => 'No calls in progress', 'elapsed' => 'Elapsed', 'recent_finished' => 'Recently finished',
    // campaigns
    'new_campaign' => 'New campaign', 'edit_campaign' => 'Edit campaign', 'show_quick_calls' => 'Show quick calls', 'show_campaigns' => 'Show campaigns',
    'cs_draft' => 'Draft', 'cs_scheduled' => 'Scheduled', 'cs_running' => 'Running', 'cs_paused' => 'Paused', 'cs_completed' => 'Completed', 'cs_stopped' => 'Stopped',
    'st_pending' => 'Pending', 'st_dialing' => 'Dialing', 'st_answered' => 'In call', 'st_completed' => 'Answered', 'st_noanswer' => 'No answer', 'st_busy' => 'Busy', 'st_congestion' => 'Congestion', 'st_failed' => 'Failed', 'st_dnc' => 'Do-not-call', 'st_cancelled' => 'Cancelled', 'st_invalid' => 'Invalid number', 'st_machine' => 'Answering machine',
    'wait_not_started' => 'Waiting for start time', 'wait_expired' => 'End time passed', 'wait_off_day' => 'Waiting: not a working day', 'wait_off_hours' => 'Waiting: outside calling hours', 'wait_holiday' => 'Waiting: holiday',
    'basic_info' => 'Basic', 'default_audio' => 'Default audio', 'none_per_contact' => 'none / per contact from the file', 'audio_hint' => 'Each contact may override the audio via the "audio" column in the import file. Manage files:',
    'priority' => 'Priority (1–10)', 'max_repeats' => 'Repeat message', 'max_repeats_hint' => 'times to replay if no key is pressed', 'ivr_timeout' => 'Wait for key (s)',
    'dialing' => 'Dialing', 'concurrent' => 'Concurrent calls', 'concurrent_hint' => 'global ceiling is %s', 'gap_ms' => 'Gap between calls (ms)', 'ring_timeout' => 'Ring timeout (s)', 'max_retries' => 'Retries', 'retry_delay_min' => 'Retry after (min)', 'retry_on' => 'Retry on', 'retries' => 'Retries', 'amd' => 'Answering machine detection',
    'advanced_overrides' => 'Advanced: caller ID / trunk overrides', 'callerid_name' => 'Caller ID name', 'callerid_number' => 'Caller ID number', 'channel_tech' => 'Channel type', 'trunk_name' => 'Trunk name', 'global' => 'global', 'use_global_prefix' => 'Use global dial prefix', 'dial_prefix' => 'Dial prefix',
    'schedule' => 'Schedule', 'start_at' => 'Start at', 'start_at_hint' => 'leave empty to start immediately when you press Start', 'end_at' => 'End at', 'end_at_hint' => 'campaign stops automatically after this time', 'use_global_window' => 'Use global calling hours', 'work_start' => 'Calling hours from', 'work_end' => 'to', 'work_days' => 'Days', 'respect_holidays' => 'Do not call on holidays',
    'day_sun' => 'Sun', 'day_mon' => 'Mon', 'day_tue' => 'Tue', 'day_wed' => 'Wed', 'day_thu' => 'Thu', 'day_fri' => 'Fri', 'day_sat' => 'Sat',
    'ivr_keys' => 'IVR keys', 'ivr_hint' => 'What happens when the callee presses a key while the message plays.', 'ivr_transfer' => 'Transfer to extension/queue', 'ivr_replay' => 'Replay message', 'ivr_hangup' => 'Hang up', 'ivr_dnc' => 'Add to do-not-call & hang up', 'ivr_play' => 'Play another file & hang up', 'ivr_tag' => 'Record answer & hang up',
    'extension_or_queue' => 'ext / queue', 'tag_placeholder' => 'e.g. interested', 'create_and_import' => 'Create & import numbers', 'name_required' => 'Name is required', 'bad_datetime' => 'Invalid date/time', 'end_before_start' => 'End time must be after start time',
    'start' => 'Start', 'start_now' => 'Start now', 'pause' => 'Pause', 'resume' => 'Resume', 'stop' => 'Stop', 'duplicate' => 'Duplicate', 'with_contacts' => 'copy contacts too', 'clear_contacts' => 'Clear contacts', 'delete_campaign' => 'Delete campaign', 'stop_before_delete' => 'Stop the campaign first',
    'campaign_started' => 'Campaign is running', 'campaign_scheduled' => 'Campaign scheduled', 'campaign_paused' => 'Campaign paused', 'campaign_stopped' => 'Campaign stopped', 'no_audio_selected' => 'Select a default audio (or per-contact audio) first', 'no_pending_contacts' => 'There are no pending numbers to call',
    'requeue' => 'Re-queue', 'requeue_hint' => 'Put contacts with the selected outcomes back into the queue (attempt counter reset).', 'requeued_n' => '%d contacts re-queued', 'summary' => 'Summary', 'responses' => 'Responses', 'no_responses_yet' => 'No key presses yet', 'answered_only' => 'Answered only', 'in_progress' => 'In progress', 'skipped' => 'Skipped', 'pressed_key' => 'Pressed a key', 'auto_refresh' => 'auto refresh',
    'add_numbers_manually' => 'Add numbers manually', 'import_contacts' => 'Import numbers', 'upload_file' => 'Upload a file', 'file_csv_xlsx' => 'CSV or Excel (.xlsx)', 'upload_and_preview' => 'Upload & preview',
    'import_hint_1' => 'One number per row. Extra columns are kept and shown in the export.', 'import_hint_2' => 'Numbers may be written with or without the leading 0, with +98, with spaces or dashes; they are normalized automatically. In Excel, format the phone column as Text to keep leading zeros (a missing 0 is restored anyway).', 'import_hint_3' => 'An optional "audio" column selects a different audio file per contact (the logical name from the Audio page).',
    'skip_for_now' => 'Skip for now', 'map_columns' => 'Map columns', 'rows' => 'rows', 'phone_column' => 'Phone column', 'name_column' => 'Name column', 'audio_column' => 'Audio column', 'column' => 'Column', 'first_row_header' => 'First row is a header', 'skip_dnc' => 'Skip do-not-call numbers', 'dedupe' => 'Skip duplicates', 'preview' => 'Preview', 'import_now' => 'Import',
    'parse_failed' => 'Could not read the file', 'file_empty' => 'The file is empty', 'import_session_expired' => 'Import session expired, upload again', 'import_failed' => 'Import failed', 'import_result' => 'Imported %d · duplicates %d · invalid %d · do-not-call %d · unknown audio %d',
    // quick
    'call_again' => 'Call this number again',
    'quick_call' => 'Quick call', 'quick_hint' => 'Call one number right now and play a message. Press 1 during the message to transfer (optional).', 'transfer_on_1' => 'Transfer to (on key 1)', 'call_now' => 'Call now', 'call_queued' => 'Call queued, it will be dialed within seconds', 'recent_quick_calls' => 'Recent quick calls',
    // audio
    'audio_files' => 'Audio files', 'no_audio_files' => 'No audio files yet.', 'used_in' => 'Used in', 'upload_audio' => 'Upload audio', 'logical_name' => 'Logical name', 'logical_name_hint' => 'used in the "audio" column of import files and the API; letters, digits, - and _', 'audio_convert_hint' => 'MP3/WAV/OGG… are converted to 8 kHz 16-bit mono WAV automatically (the format Asterisk plays best).',
    'no_sox_warning' => 'sox / ffmpeg not found: only WAV/GSM files can be converted (via asterisk). Install sox: yum install sox', 'bad_audio_type' => 'Unsupported audio type', 'audio_name_exists' => 'An audio file with this name already exists', 'convert_failed' => 'Audio conversion failed', 'audio_in_use' => 'Audio is used by an active campaign', 'audio_uploaded' => 'Audio "%s" added (%d s)',
    // dnc
    'dnc_list' => 'Do-not-call list', 'add_to_dnc' => 'Add numbers', 'dnc_hint' => 'Numbers here are never dialed by any campaign. Callees can add themselves via an IVR key.', 'dnc_added' => '%d numbers added', 'import_file' => 'Import from file',
    // reports
    'from' => 'From', 'to' => 'To', 'all_campaigns' => 'All campaigns', 'total_calls' => 'Calls', 'avg' => 'avg', 'calls_per_day' => 'Calls per day', 'calls_per_hour' => 'Calls by hour of day', 'by_campaign' => 'By campaign', 'dtmf_distribution' => 'Keys pressed',
    // settings
    'trunk_cid_placeholder' => 'line number', 'trunk_cid_hint' => 'Caller ID number per trunk: most providers reject calls whose From user is not the line/account number (403 Forbidden). Filled from the trunk\'s Outbound CID in Issabel; empty = global caller ID.', 'trunk_cids_updated' => '%d trunk caller IDs filled from Issabel',
    'trunk_pool' => 'Trunk pool (managed by this app)', 'trunk_pool_hint' => 'Each call goes out directly on one trunk of the pool with a free channel, so Issabel outbound routes and their automatic failover are bypassed: a number rings exactly once and is re-dialed only by the campaign retry rules. Total concurrency = sum of channels. The trunk prefix (if any) is applied, the global dial prefix is not.', 'trunk_pool_inactive' => 'The pool is not in use: set "Channel type" above to "Trunk pool" and save.', 'import_pbx_trunks' => 'Add trunks from Issabel', 'trunks_imported' => '%d trunks added (1 channel each - adjust)', 'trunk_exists' => 'This trunk is already in the pool', 'tech' => 'Type', 'trunk_channel_id' => 'Trunk (channel id)', 'channels' => 'Channels', 'wait_trunks_busy' => 'Waiting: all trunk channels are busy',
    'import_iran_holidays' => 'Add official holidays of Iran', 'import_iran_holidays_hint' => 'Solar holidays are exact; lunar (religious) ones follow the tabular Hijri calendar and may be one day off the announced date - check and adjust.', 'iran_holidays_added' => '%d holidays added for %d', 'lunar_mark' => '(lunar)', 'toggle_theme' => 'Dark / light mode',
    'outbound_settings' => 'Outbound calling', 'via_dialplan' => 'via Issabel outbound routes', 'custom_template' => 'Custom template', 'channel_tech_hint' => 'Local = use Issabel outbound routes/trunk failover (recommended). SIP/PJSIP = dial one trunk directly.', 'channel_template' => 'Custom channel template', 'outbound_context' => 'Outbound context',
    'dial_prefix_hint' => 'prepended to every number (e.g. 9 if your outbound route requires it)', 'country_code' => 'Country code', 'detected_trunks' => 'Trunks found in Issabel', 'disabled' => 'disabled',
    'capacity_defaults' => 'Capacity & defaults', 'global_max_concurrent' => 'Max concurrent calls (all campaigns)', 'global_max_hint' => 'never exceed your trunk channel count', 'default_concurrent' => 'Default per campaign', 'default_gap_ms' => 'Default gap (ms)', 'default_ring_timeout' => 'Default ring timeout (s)', 'default_max_retries' => 'Default retries', 'default_retry_delay_min' => 'Default retry delay (min)',
    'cdr_lookup' => 'Read talk time from CDR', 'stale_call_minutes' => 'Stale call timeout (min)', 'global_window' => 'Global calling hours', 'security_ui' => 'Security & interface', 'login_max_attempts' => 'Login attempts before lock (0=off)', 'login_lock_minutes' => 'Lock minutes', 'retention_days' => 'Keep history (days)', 'retention_hint' => '0 = forever; cleanup runs nightly',
    'issabel_login' => 'Allow Issabel panel users to sign in', 'issabel_admin_role' => 'Role for Issabel admins', 'api_enabled' => 'REST API', 'ui_lang' => 'Default language', 'ami_hint' => 'AMI credentials are written by the installer into config.php (manager_custom.conf). Change them there if needed and restart the dialer service.', 'test_ami' => 'Test AMI connection', 'ami_ok' => 'AMI connection OK',
    'holidays' => 'Holidays', 'holidays_hint' => 'No calls are placed on these dates (for campaigns with "Do not call on holidays").',
    // users
    'only_root_manages_admins' => 'Only the superuser root can change other administrators.', 'reset_issabel_user_hint' => 'Reset this Issabel user for this app: removes the assigned role, app-only password and API keys; on next sign-in they get the default role again.',
    'root_protected' => "The superuser 'root' can only be changed by root.", 'only_root' => 'Only the superuser root can do this.', 'only_root_grants_admin' => 'Only the superuser root can grant the administrator role.', 'not_root_notice' => "You are not the superuser: the account 'root' and other administrators are read-only here, the administrator role can only be granted by root, and app-only passwords for Issabel users are set by root.", 'app_password' => 'app-only password', 'app_password_hint' => 'Optional password valid only for this app; the Issabel panel password keeps working too. Leave empty to keep.',
    'issabel_users' => 'Issabel panel users', 'issabel_users_hint' => 'Users of the Issabel panel and what they get when they sign in here with their panel password.', 'issabel_login_disabled' => 'Sign-in with Issabel panel users is disabled in settings.', 'issabel_acl_unreachable' => 'Cannot read the Issabel user store (/var/www/db/acl.db). Run: console.php issabel:test', 'issabel_groups' => 'Issabel groups', 'access_state' => 'Access here',
    'access_auto' => 'not signed in yet', 'access_linked' => 'signed in / assigned', 'access_local' => 'local account with this name', 'managed_below' => 'managed in the local users list below', 'issabel_user_shadowed' => "A local account named '%s' exists; manage it in the local users list.", 'local_users' => 'Local users of this app',
    'display_name' => 'Display name', 'last_login' => 'Last login', 'new_password' => 'New password', 'new_user' => 'New user', 'password_min' => 'Password must be at least 8 characters', 'user_exists' => 'Username already exists', 'cannot_delete_self' => 'You cannot delete yourself', 'profile' => 'Profile', 'current_password' => 'Current password', 'wrong_current_password' => 'Current password is wrong', 'issabel_user_no_password' => 'Password of Issabel users is managed in the Issabel panel',
    // api
    'api_keys' => 'API keys', 'new_key_notice' => 'Copy this key now, it will not be shown again:', 'allowed_ips' => 'Allowed IPs', 'allowed_ips_placeholder' => 'IPs, comma separated (empty = any)', 'last_used' => 'Last used', 'key_name' => 'Key name (e.g. CRM)', 'create_key' => 'Create key', 'api_docs' => 'How to use the API', 'api_intro' => 'Send the key in the header',
    'api_ex_call' => 'call one number now', 'api_ex_status' => 'check the result of that call', 'api_ex_campaign' => 'create a campaign with contacts and start it', 'api_ex_results' => 'read results', 'api_ex_other' => 'other endpoints',
    // system
    'dialer_daemon' => 'Dialer service', 'running' => 'running', 'not_running' => 'not running', 'connected' => 'connected', 'disconnected' => 'disconnected', 'last_error' => 'Last error', 'daemon_down_hint' => 'The dialer service is not running. No calls will be placed until it is started:', 'environment' => 'Environment', 'logs' => 'Logs', 'audit_log' => 'Audit log', 'pick_a_log' => 'Pick a log above', 'object' => 'Object', 'details' => 'Details',
);
