<?php
return array(
    // nav
    'nav_dashboard' => 'داشبورد', 'nav_campaigns' => 'کمپین‌ها', 'nav_quick' => 'تماس تکی', 'nav_audio' => 'فایل‌های صوتی', 'nav_dnc' => 'لیست سیاه',
    'nav_reports' => 'گزارش‌ها', 'nav_settings' => 'تنظیمات', 'nav_users' => 'کاربران', 'nav_api' => 'کلیدهای API', 'nav_system' => 'سیستم',
    // auth
    'login' => 'ورود', 'logout' => 'خروج', 'username' => 'نام کاربری', 'password' => 'رمز عبور', 'login_intro' => 'سامانه‌ی تماس خودکار برای Issabel / Elastix',
    'login_failed' => 'نام کاربری یا رمز عبور اشتباه است', 'login_locked' => 'تلاش‌های ناموفق زیاد بود. کمی بعد دوباره امتحان کنید.', 'login_root_hint' => 'سوپریوزر این برنامه: root.', 'login_issabel_hint' => 'با کاربران پنل Issabel (مثل admin) هم می‌توانید وارد شوید.',
    'forbidden' => 'شما اجازه‌ی این کار را ندارید', 'not_found' => 'صفحه پیدا نشد', 'csrf_failed' => 'فرم منقضی شده، دوباره تلاش کنید', 'server_error' => 'خطای داخلی؛ لاگ‌ها را ببینید', 'back_home' => 'بازگشت به داشبورد',
    'role_admin' => 'مدیر', 'role_operator' => 'اپراتور', 'role_viewer' => 'بیننده',
    'role_admin_desc' => 'دسترسی کامل: تنظیمات، کاربران، حذف کمپین.', 'role_operator_desc' => 'ساخت و اجرای کمپین، فایل صوتی، لیست سیاه، کلید API.', 'role_viewer_desc' => 'فقط مشاهده‌ی کمپین‌ها و گزارش‌ها.',
    // common
    'save' => 'ذخیره', 'saved' => 'ذخیره شد', 'cancel' => 'انصراف', 'delete' => 'حذف', 'deleted' => 'حذف شد', 'edit' => 'ویرایش', 'create' => 'ایجاد', 'add' => 'افزودن', 'done' => 'انجام شد', 'yes' => 'بله', 'no' => 'خیر', 'on' => 'فعال', 'off' => 'غیرفعال',
    'name' => 'نام', 'description' => 'توضیحات', 'status' => 'وضعیت', 'search' => 'جستجو…', 'filter' => 'فیلتر', 'all' => 'همه', 'all_statuses' => 'همه‌ی وضعیت‌ها', 'nothing_here' => 'هنوز چیزی اینجا نیست', 'none' => 'هیچ',
    'created_at' => 'ایجاد', 'created_by' => 'توسط', 'started_at' => 'شروع', 'finished_at' => 'پایان', 'time' => 'زمان', 'count' => 'تعداد', 'title' => 'عنوان', 'key' => 'کلید', 'tag' => 'برچسب', 'target' => 'مقصد', 'action' => 'عملیات',
    'phone' => 'شماره', 'contacts' => 'مخاطبین', 'audio' => 'فایل صوتی', 'campaign' => 'کمپین', 'progress' => 'پیشرفت', 'answered' => 'پاسخ‌داده', 'duration' => 'مدت', 'dtmf' => 'کلید فشرده', 'result_tag' => 'نتیجه',
    'hangup_cause' => 'علت قطع', 'raw_phone' => 'شماره‌ی اصلی', 'attempts' => 'تلاش‌ها', 'attempt' => 'تلاش', 'last_attempt' => 'آخرین تلاش', 'answered_at' => 'زمان پاسخ', 'ended_at' => 'زمان پایان', 'channel' => 'کانال', 'note' => 'یادداشت',
    'invalid_input' => 'ورودی نامعتبر', 'unknown_action' => 'عملیات ناشناخته', 'confirm_delete' => 'برای همیشه حذف شود؟', 'confirm_stop' => 'کمپین متوقف شود؟ شماره‌های در انتظار لغو می‌شوند.', 'confirm_clear' => 'همه‌ی مخاطبین و تاریخچه‌ی تماس این کمپین پاک شود؟',
    'upload_error' => 'آپلود ناموفق بود', 'file_too_big' => 'فایل خیلی بزرگ است', 'file' => 'فایل', 'upload' => 'آپلود', 'size' => 'حجم', 'play' => 'پخش', 'rename' => 'تغییر نام', 'source' => 'منبع', 'reason' => 'دلیل', 'user' => 'کاربر', 'users' => 'کاربران', 'role' => 'نقش', 'active' => 'فعال',
    // dashboard
    'calls_today' => 'تماس‌های امروز', 'talk_time' => 'زمان مکالمه', 'active_campaigns' => 'کمپین‌های فعال', 'no_active_campaigns' => 'کمپین فعالی وجود ندارد', 'live_calls' => 'تماس‌های زنده', 'no_live_calls' => 'تماسی در جریان نیست', 'elapsed' => 'گذشته', 'recent_finished' => 'اخیراً تمام‌شده',
    // campaigns
    'new_campaign' => 'کمپین جدید', 'edit_campaign' => 'ویرایش کمپین', 'show_quick_calls' => 'نمایش تماس‌های تکی', 'show_campaigns' => 'نمایش کمپین‌ها',
    'cs_draft' => 'پیش‌نویس', 'cs_scheduled' => 'زمان‌بندی‌شده', 'cs_running' => 'در حال اجرا', 'cs_paused' => 'متوقف موقت', 'cs_completed' => 'تکمیل‌شده', 'cs_stopped' => 'متوقف‌شده',
    'st_pending' => 'در انتظار', 'st_dialing' => 'در حال شماره‌گیری', 'st_answered' => 'در مکالمه', 'st_completed' => 'پاسخ داد', 'st_noanswer' => 'بی‌پاسخ', 'st_busy' => 'مشغول', 'st_congestion' => 'خط پر / ترانک', 'st_failed' => 'ناموفق', 'st_dnc' => 'لیست سیاه', 'st_cancelled' => 'لغوشده', 'st_invalid' => 'شماره نامعتبر', 'st_machine' => 'منشی تلفنی',
    'wait_not_started' => 'در انتظار زمان شروع', 'wait_expired' => 'زمان پایان گذشته', 'wait_off_day' => 'در انتظار: امروز روز کاری نیست', 'wait_off_hours' => 'در انتظار: خارج از ساعت تماس', 'wait_holiday' => 'در انتظار: تعطیل رسمی',
    'basic_info' => 'اطلاعات پایه', 'default_audio' => 'فایل صوتی پیش‌فرض', 'none_per_contact' => 'هیچ / برای هر شماره از فایل', 'audio_hint' => 'هر شماره می‌تواند با ستون «audio» در فایل ورودی، فایل صوتی متفاوتی داشته باشد. مدیریت فایل‌ها:',
    'priority' => 'اولویت (۱ تا ۱۰)', 'max_repeats' => 'تکرار پیام', 'max_repeats_hint' => 'اگر کلیدی زده نشد چند بار دوباره پخش شود', 'ivr_timeout' => 'مهلت فشردن کلید (ثانیه)',
    'dialing' => 'شماره‌گیری', 'concurrent' => 'تماس هم‌زمان', 'concurrent_hint' => 'سقف سراسری %s است', 'gap_ms' => 'فاصله بین تماس‌ها (میلی‌ثانیه)', 'ring_timeout' => 'مهلت زنگ (ثانیه)', 'max_retries' => 'تلاش مجدد', 'retry_delay_min' => 'فاصله تلاش مجدد (دقیقه)', 'retry_on' => 'تلاش مجدد برای', 'retries' => 'تلاش مجدد', 'amd' => 'تشخیص منشی تلفنی',
    'advanced_overrides' => 'پیشرفته: کالر آی‌دی / ترانک اختصاصی', 'callerid_name' => 'نام کالر آی‌دی', 'callerid_number' => 'شماره‌ی کالر آی‌دی', 'channel_tech' => 'نوع کانال', 'trunk_name' => 'نام ترانک', 'global' => 'سراسری', 'use_global_prefix' => 'استفاده از پیش‌شماره‌ی سراسری', 'dial_prefix' => 'پیش‌شماره',
    'schedule' => 'زمان‌بندی', 'start_at' => 'شروع در', 'start_at_hint' => 'خالی بگذارید تا با زدن «شروع» بلافاصله آغاز شود', 'end_at' => 'پایان در', 'end_at_hint' => 'کمپین بعد از این زمان خودکار متوقف می‌شود', 'use_global_window' => 'استفاده از ساعت کاری سراسری', 'work_start' => 'ساعت تماس از', 'work_end' => 'تا', 'work_days' => 'روزها', 'respect_holidays' => 'در تعطیلات تماس گرفته نشود',
    'day_sun' => 'یک‌شنبه', 'day_mon' => 'دوشنبه', 'day_tue' => 'سه‌شنبه', 'day_wed' => 'چهارشنبه', 'day_thu' => 'پنج‌شنبه', 'day_fri' => 'جمعه', 'day_sat' => 'شنبه',
    'ivr_keys' => 'کلیدهای IVR', 'ivr_hint' => 'وقتی مخاطب حین پخش پیام کلیدی را می‌زند چه اتفاقی بیفتد.', 'ivr_transfer' => 'انتقال به داخلی / صف', 'ivr_replay' => 'پخش مجدد پیام', 'ivr_hangup' => 'قطع تماس', 'ivr_dnc' => 'افزودن به لیست سیاه و قطع', 'ivr_play' => 'پخش فایل دیگر و قطع', 'ivr_tag' => 'ثبت پاسخ و قطع',
    'extension_or_queue' => 'داخلی / صف', 'tag_placeholder' => 'مثلاً علاقه‌مند', 'create_and_import' => 'ایجاد و ورود شماره‌ها', 'name_required' => 'نام الزامی است', 'bad_datetime' => 'تاریخ/زمان نامعتبر', 'end_before_start' => 'زمان پایان باید بعد از شروع باشد',
    'start' => 'شروع', 'start_now' => 'شروع همین حالا', 'pause' => 'توقف موقت', 'resume' => 'ادامه', 'stop' => 'توقف کامل', 'duplicate' => 'کپی کمپین', 'with_contacts' => 'مخاطبین هم کپی شوند', 'clear_contacts' => 'پاک کردن مخاطبین', 'delete_campaign' => 'حذف کمپین', 'stop_before_delete' => 'اول کمپین را متوقف کنید',
    'campaign_started' => 'کمپین در حال اجراست', 'campaign_scheduled' => 'کمپین زمان‌بندی شد', 'campaign_paused' => 'کمپین موقتاً متوقف شد', 'campaign_stopped' => 'کمپین متوقف شد', 'no_audio_selected' => 'اول فایل صوتی پیش‌فرض (یا برای هر شماره) انتخاب کنید', 'no_pending_contacts' => 'شماره‌ای در انتظار تماس نیست',
    'requeue' => 'بازگشت به صف', 'requeue_hint' => 'شماره‌هایی با نتایج انتخاب‌شده دوباره در صف تماس قرار می‌گیرند (شمارنده‌ی تلاش صفر می‌شود).', 'requeued_n' => '%d شماره به صف برگشت', 'summary' => 'خلاصه', 'responses' => 'پاسخ‌ها', 'no_responses_yet' => 'هنوز کلیدی فشرده نشده', 'answered_only' => 'فقط پاسخ‌داده‌ها', 'in_progress' => 'در جریان', 'skipped' => 'رد شده', 'pressed_key' => 'کلید زده', 'auto_refresh' => 'به‌روزرسانی خودکار',
    'add_numbers_manually' => 'افزودن دستی شماره', 'import_contacts' => 'ورود شماره‌ها', 'upload_file' => 'آپلود فایل', 'file_csv_xlsx' => 'CSV یا Excel (.xlsx)', 'upload_and_preview' => 'آپلود و پیش‌نمایش',
    'import_hint_1' => 'هر ردیف یک شماره. ستون‌های اضافه نگه داشته می‌شوند و در خروجی اکسل می‌آیند.', 'import_hint_2' => 'شماره‌ها می‌توانند با یا بدون صفر اول، با +98، با فاصله یا خط‌تیره باشند؛ خودکار اصلاح می‌شوند. در اکسل ستون شماره را Text کنید تا صفر اول نپرد (اگر هم پرید، خودمان برمی‌گردانیم).', 'import_hint_3' => 'ستون اختیاری «audio» برای هر شماره فایل صوتی متفاوتی انتخاب می‌کند (نام منطقی از صفحه‌ی فایل‌های صوتی).',
    'skip_for_now' => 'فعلاً رد شو', 'map_columns' => 'تعیین ستون‌ها', 'rows' => 'ردیف', 'phone_column' => 'ستون شماره', 'name_column' => 'ستون نام', 'audio_column' => 'ستون فایل صوتی', 'column' => 'ستون', 'first_row_header' => 'ردیف اول عنوان است', 'skip_dnc' => 'شماره‌های لیست سیاه رد شوند', 'dedupe' => 'تکراری‌ها رد شوند', 'preview' => 'پیش‌نمایش', 'import_now' => 'ورود شماره‌ها',
    'parse_failed' => 'فایل قابل خواندن نبود', 'file_empty' => 'فایل خالی است', 'import_session_expired' => 'نشست ورود منقضی شد؛ دوباره آپلود کنید', 'import_failed' => 'ورود ناموفق بود', 'import_result' => '%d شماره وارد شد · تکراری %d · نامعتبر %d · لیست سیاه %d · فایل صوتی ناشناخته %d',
    // quick
    'quick_call' => 'تماس تکی', 'quick_hint' => 'همین حالا با یک شماره تماس بگیر و پیام را پخش کن. با زدن ۱ حین پیام منتقل می‌شود (اختیاری).', 'transfer_on_1' => 'انتقال به (با کلید ۱)', 'call_now' => 'تماس بگیر', 'call_queued' => 'تماس در صف قرار گرفت و تا چند ثانیه‌ی دیگر گرفته می‌شود', 'recent_quick_calls' => 'تماس‌های تکی اخیر',
    // audio
    'audio_files' => 'فایل‌های صوتی', 'no_audio_files' => 'هنوز فایل صوتی ندارید.', 'used_in' => 'استفاده در', 'upload_audio' => 'آپلود فایل صوتی', 'logical_name' => 'نام منطقی', 'logical_name_hint' => 'در ستون «audio» فایل‌های ورودی و API استفاده می‌شود؛ حروف، عدد، - و _', 'audio_convert_hint' => 'MP3/WAV/OGG… خودکار به WAV هشت کیلوهرتز ۱۶ بیت مونو تبدیل می‌شوند (بهترین فرمت برای Asterisk).',
    'no_sox_warning' => 'sox / ffmpeg پیدا نشد: فقط WAV/GSM تبدیل می‌شوند (با خود asterisk). نصب: yum install sox', 'bad_audio_type' => 'نوع فایل صوتی پشتیبانی نمی‌شود', 'audio_name_exists' => 'فایل صوتی با این نام وجود دارد', 'convert_failed' => 'تبدیل فایل صوتی ناموفق بود', 'audio_in_use' => 'این فایل در کمپین فعالی استفاده می‌شود', 'audio_uploaded' => 'فایل «%s» اضافه شد (%d ثانیه)',
    // dnc
    'dnc_list' => 'لیست سیاه (عدم تماس)', 'add_to_dnc' => 'افزودن شماره', 'dnc_hint' => 'با شماره‌های این لیست هیچ کمپینی تماس نمی‌گیرد. مخاطب می‌تواند با کلید IVR خودش را اضافه کند.', 'dnc_added' => '%d شماره اضافه شد', 'import_file' => 'ورود از فایل',
    // reports
    'from' => 'از', 'to' => 'تا', 'all_campaigns' => 'همه‌ی کمپین‌ها', 'total_calls' => 'تماس‌ها', 'avg' => 'میانگین', 'calls_per_day' => 'تماس در روز', 'calls_per_hour' => 'تماس بر حسب ساعت روز', 'by_campaign' => 'به تفکیک کمپین', 'dtmf_distribution' => 'کلیدهای فشرده‌شده',
    // settings
    'outbound_settings' => 'تماس خروجی', 'via_dialplan' => 'از طریق مسیرهای خروجی Issabel', 'custom_template' => 'الگوی دلخواه', 'channel_tech_hint' => 'Local = استفاده از Outbound Route و failover ترانک خود Issabel (پیشنهادی). SIP/PJSIP = تماس مستقیم از یک ترانک.', 'channel_template' => 'الگوی کانال دلخواه', 'outbound_context' => 'کانتکست خروجی',
    'dial_prefix_hint' => 'به ابتدای همه‌ی شماره‌ها اضافه می‌شود (مثلاً 9 اگر مسیر خروجی لازم دارد)', 'country_code' => 'کد کشور', 'detected_trunks' => 'ترانک‌های پیدا شده در Issabel', 'disabled' => 'غیرفعال',
    'capacity_defaults' => 'ظرفیت و پیش‌فرض‌ها', 'global_max_concurrent' => 'حداکثر تماس هم‌زمان (کل کمپین‌ها)', 'global_max_hint' => 'از تعداد کانال ترانک بیشتر نگذارید', 'default_concurrent' => 'پیش‌فرض هر کمپین', 'default_gap_ms' => 'فاصله پیش‌فرض (میلی‌ثانیه)', 'default_ring_timeout' => 'مهلت زنگ پیش‌فرض (ثانیه)', 'default_max_retries' => 'تلاش مجدد پیش‌فرض', 'default_retry_delay_min' => 'فاصله تلاش مجدد پیش‌فرض (دقیقه)',
    'cdr_lookup' => 'خواندن زمان مکالمه از CDR', 'stale_call_minutes' => 'مهلت تماس معلق (دقیقه)', 'global_window' => 'ساعت کاری سراسری', 'security_ui' => 'امنیت و رابط', 'login_max_attempts' => 'تلاش ورود تا قفل (0=خاموش)', 'login_lock_minutes' => 'مدت قفل (دقیقه)', 'retention_days' => 'نگه‌داری تاریخچه (روز)', 'retention_hint' => '0 = همیشه؛ پاک‌سازی شبانه انجام می‌شود',
    'issabel_login' => 'ورود با کاربران پنل Issabel', 'issabel_admin_role' => 'نقش ادمین‌های Issabel', 'api_enabled' => 'REST API', 'ui_lang' => 'زبان پیش‌فرض', 'ami_hint' => 'مشخصات AMI توسط نصاب در config.php و manager_custom.conf نوشته شده. در صورت تغییر، سرویس dialer را ری‌استارت کنید.', 'test_ami' => 'تست اتصال AMI', 'ami_ok' => 'اتصال AMI برقرار است',
    'holidays' => 'تعطیلات', 'holidays_hint' => 'در این تاریخ‌ها تماسی گرفته نمی‌شود (برای کمپین‌هایی که گزینه‌ی تعطیلات فعال دارند).',
    // users
    'root_protected' => 'سوپریوزر root فقط توسط خود root قابل تغییر است.', 'only_root' => 'فقط سوپریوزر root می‌تواند این کار را بکند.', 'only_root_grants_admin' => 'فقط سوپریوزر root می‌تواند نقش مدیر بدهد.', 'not_root_notice' => 'شما سوپریوزر نیستید: حساب root اینجا فقط‌خواندنی است، نقش مدیر را فقط root می‌تواند بدهد، و رمز اختصاصی برنامه برای کاربران Issabel را root تعیین می‌کند.', 'app_password' => 'رمز اختصاصی برنامه', 'app_password_hint' => 'رمز اختیاری که فقط در این برنامه معتبر است؛ رمز پنل Issabel هم همچنان کار می‌کند. خالی = بدون تغییر.',
    'issabel_users' => 'کاربران پنل Issabel', 'issabel_users_hint' => 'کاربران پنل Issabel و سطح دسترسی‌شان وقتی با رمز پنل وارد این برنامه می‌شوند.', 'issabel_login_disabled' => 'ورود با کاربران پنل Issabel در تنظیمات غیرفعال است.', 'issabel_acl_unreachable' => 'فایل کاربران Issabel (/var/www/db/acl.db) قابل خواندن نیست. اجرا کنید: console.php issabel:test', 'issabel_groups' => 'گروه‌های Issabel', 'access_state' => 'وضعیت دسترسی',
    'access_auto' => 'هنوز وارد نشده', 'access_linked' => 'وارد شده / تعیین‌شده', 'access_local' => 'حساب محلی هم‌نام دارد', 'managed_below' => 'در لیست کاربران محلی پایین مدیریت می‌شود', 'issabel_user_shadowed' => 'حساب محلی به نام «%s» وجود دارد؛ آن را در لیست کاربران محلی مدیریت کنید.', 'local_users' => 'کاربران محلی این برنامه',
    'display_name' => 'نام نمایشی', 'last_login' => 'آخرین ورود', 'new_password' => 'رمز جدید', 'new_user' => 'کاربر جدید', 'password_min' => 'رمز حداقل ۸ کاراکتر باشد', 'user_exists' => 'این نام کاربری وجود دارد', 'cannot_delete_self' => 'نمی‌توانید خودتان را حذف کنید', 'profile' => 'پروفایل', 'current_password' => 'رمز فعلی', 'wrong_current_password' => 'رمز فعلی اشتباه است', 'issabel_user_no_password' => 'رمز کاربران Issabel از پنل Issabel مدیریت می‌شود',
    // api
    'api_keys' => 'کلیدهای API', 'new_key_notice' => 'این کلید را همین حالا کپی کنید؛ دوباره نمایش داده نمی‌شود:', 'allowed_ips' => 'IPهای مجاز', 'allowed_ips_placeholder' => 'IPها با ویرگول (خالی = همه)', 'last_used' => 'آخرین استفاده', 'key_name' => 'نام کلید (مثلاً CRM)', 'create_key' => 'ساخت کلید', 'api_docs' => 'نحوه‌ی استفاده از API', 'api_intro' => 'کلید را در هدر بفرستید:',
    'api_ex_call' => 'تماس فوری با یک شماره', 'api_ex_status' => 'نتیجه‌ی همان تماس', 'api_ex_campaign' => 'ساخت کمپین با شماره‌ها و شروع آن', 'api_ex_results' => 'خواندن نتایج', 'api_ex_other' => 'سایر endpointها',
    // system
    'dialer_daemon' => 'سرویس شماره‌گیر', 'running' => 'در حال اجرا', 'not_running' => 'اجرا نمی‌شود', 'connected' => 'متصل', 'disconnected' => 'قطع', 'last_error' => 'آخرین خطا', 'daemon_down_hint' => 'سرویس شماره‌گیر اجرا نمی‌شود؛ تا راه‌اندازی آن هیچ تماسی گرفته نمی‌شود:', 'environment' => 'محیط', 'logs' => 'لاگ‌ها', 'audit_log' => 'لاگ رخدادها', 'pick_a_log' => 'یکی از لاگ‌ها را انتخاب کنید', 'object' => 'موضوع', 'details' => 'جزئیات',
);
