<link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="../assets/vendor/dist/font-awesome/css/font-awesome.css">
<link rel="stylesheet" href="../assets/vendor/dist/Ionicons/css/ionicons.min.css">
<link rel="stylesheet" href="../assets/vendor/dist/css/skins/_all-skins.min.css">
<link rel="stylesheet" href="../assets/vendor/plugins/morris/morris.css">
<link rel="stylesheet" href="../assets/vendor/plugins/datepicker/datepicker3.css">
<link rel="stylesheet" href="../assets/vendor/plugins/daterangepicker/daterangepicker-bs3.css">
<link rel="stylesheet" href="../assets/vendor/plugins/datatables/dataTables.bootstrap.css">
<link rel="stylesheet" href="../assets/vendor/plugins/select2/select2.min.css">
<link rel="stylesheet" href="../assets/vendor/dist/css/AdminLTE.css">